services:
  - type: web
    name: introvertchat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9
      - key: DATABASE_URL
        fromDatabase:
          name: introvertchat-db
          property: connectionString

databases:
  - name: introvertchat-db
    databaseName: introvertchat
    user: introvertchat_user
